global:
  scrape_interval: 5s
  external_labels:
    namespace: local

rule_files:
  - /etc/prometheus/recording-rules.yml
  - /etc/prometheus/alerting-rules.yml

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: [ '0.0.0.0:9090' ]
        labels:
          container: 'prometheus'

  - job_name: git
    static_configs:
      - targets: [ '172.16.101.75:9100' ]
        labels:
          container: 'prometheus'

  - job_name: monit
    static_configs:
      - targets: [ '172.16.101.74:9100' ]
        labels:
          container: 'prometheus'

  - job_name: app1
    static_configs:
      - targets: [ '172.16.101.71:9100' ]
        labels:
          container: 'prometheus'

  - job_name: app2
    static_configs:
      - targets: [ '172.16.101.72:9100' ]
        labels:
          container: 'prometheus'

  - job_name: db
    static_configs:
      - targets: [ '172.16.101.73:9100' ]
        labels:
          container: 'prometheus'          

  - job_name: web
    static_configs:
      - targets: [ '172.16.101.70:9100' ]
        labels:
          container: 'prometheus'

  - job_name: alertmanager
    static_configs:
      - targets: [ 'alertmanager:9093' ]
        labels:
          container: 'alertmanager'

  - job_name: node-exporter
    static_configs:
      - targets: [ 'node-exporter:9100' ]
        labels:
          container: 'node-exporter'

  - job_name: cadvisor
    static_configs:
      - targets: [ 'cadvisor:8080' ]
        labels:
          container: 'cadvisor'

  - job_name: telegraf db
    scrape_interval: 10s
    static_configs:
      - targets: [ '192.168.0.171:9273' ]
        labels:
          container: 'prometheus'
